### ISSUE TITLE
Train data

### ISSUE THREAD

**Issue by jovian-2wang** [Deep-imagelab/AWAN#2]
Hello, can you share your training data set? I can't find this part of the data set from the Internet. Thank you

**Comment by Deep-imagelab** [comment]
You can get it in the participate tab of the link "https://competitions.codalab.org/competitions/22225".

**Comment by wangjiangwei123** [comment]
是的，我上了这个网页，这一块是没有链接的，它的数据因为比赛结束了，数据不能下载了，链接已经打不开了，我注册了也发现没用，所以情急之下，想问你们可否提供一下数据集，因为我自己做的数据集一直不能读取
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Deep-imagelab"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 上午10:19
收件人:&nbsp;"Deep-imagelab/AWAN"<AWAN@noreply.github.com&gt;;
抄送:&nbsp;"keep on"<1198346472@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Deep-imagelab/AWAN] Train data (#2)





 
You can get it in the participate tab of the link "https://competitions.codalab.org/competitions/22225".

**Comment by Deep-imagelab** [comment]
注册之后是需要等待通过的，通过之后是可以下载数据的；这部分数据是由光谱重建大赛官方发布的，所有权属于官方，我建议你可以发送邮件给官方索要一下数据，我这边分享官方所有权的数据是不合适的；根据你邮件里说的，你跑代码遇到了问题，可以具体说一下是什么问题吗，我很乐意帮你解决代码问题。

**Comment by wangjiangwei123** [comment]
好的，好的！我想知道clean数据集是rgb 1392*1300jpg格式，还是1392*1300. mat的31通道数据，real的数据集是512*482rgbJPG.还是512*482的.mat 的31通道数据，还是两者都有



---Original---

**Comment by wangjiangwei123** [comment]
我在谷歌网盘的那个连接上也没找到，这两个是没有的，还是需要自己训练出来的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Deep-imagelab"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 上午10:37
收件人:&nbsp;"Deep-imagelab/AWAN"<AWAN@noreply.github.com&gt;;
抄送:&nbsp;"keep on"<1198346472@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Deep-imagelab/AWAN] Train data (#2)





 
注册之后是需要等待通过的，通过之后是可以下载数据的；这部分数据是由光谱重建大赛官方发布的，所有权属于官方，我建议你可以发送邮件给官方索要一下数据，我这边分享官方所有权的数据是不合适的；根据你邮件里说的，你跑代码遇到了问题，可以具体说一下是什么问题吗，我很乐意帮你解决代码问题。

**Comment by wangjiangwei123** [comment]
还有这是我自己放的31通道.mat数据集，为什么会出现这种情况

**Comment by jovian-2wang** [comment]
您好，我已经咨询过官方了，但官方让我联系你们要数据集，您看看可否提供给我，我知道数据集太大，提供几个train数据集就行，请求您了please !

---Original---
From: "Isabelle Guyon"<guyon@chalearn.org&gt;
Date: Sat, Jul 4, 2020 00:19 AM
To: "keep on"<1198346472@qq.com&gt;;
Cc: "info@codalab.org"<info@codalab.org&gt;;
Subject: Re: need help


you reach codalab admins, please contact your competition organizers.
Isabelle

&gt; On Jul 2, 2020, at 8:20 PM, keep on <1198346472@qq.com&gt; wrote:
&gt; 
&gt; Hello, I have registered, but I want to obtain ntire 2020 spectral reconstruction challenge - track 1: clean, can I apply for the dataset of training

**Comment by msn321** [comment]
@Deep-imagelab  Hello, I have run the file / awan_ RealWorld/test/valid_ After model1.py, why is there an error: oserror: unable to create file (unable to open file: name '). / valid_ results1/NTIRE2020_ Validation_ RealWorld\ARAD_ HS_ 0451.mat', errno = 2, error message = 'No such file or directory', flags = 13, o_ flags = 302)

**Comment by msn321** [comment]
Hello，running  clean / test / valid_ result.py  ，whether you are running out of memory? Thanks.

**Comment by msn321** [comment]
@jovian-2wang 
Hello，what are the results of running train_data_preprocess.py and valid_data_preprocess.py? I feel my fault.Thank you.

**Comment by msn321** [comment]
@Deep-imagelab Hello, when I was running main.py file, I encountered the following problem. I searched for information and tried several solutions, but failed to run it successfully. Do you know the reason?How can it be modified? Thank you

Problem:
D:\software\anaconda3\envs\pytorch\python.exe E:/IPIC-AWAN-master/AWAN_Clean/train/main.py

loading dataset ...
Train1:0,Train2:0,Train3:0,Train4:0,
Validation set samples:  0

building models_baseline ...
Parameters number is  17461617
Traceback (most recent call last):
  File "E:/IPIC-AWAN-master/AWAN_Clean/train/main.py", line 186, in <module>
    main()
  File "E:/IPIC-AWAN-master/AWAN_Clean/train/main.py", line 95, in main
    train_loss, iteration, lr = train(train_loader, model, criterion_train, optimizer, epoch, iteration, opt.init_lr, opt.decay_power, opt.trade_off)
  File "E:/IPIC-AWAN-master/AWAN_Clean/train/main.py", line 145, in train
    return losses.avg, iteration, lr
UnboundLocalError: local variable 'lr' referenced before assignment

**Comment by Deep-imagelab** [comment]
> @Deep-imagelab Hello, when I was running main.py file, I encountered the following problem. I searched for information and tried several solutions, but failed to run it successfully. Do you know the reason?How can it be modified? Thank you
> 
> Problem:
> D:\software\anaconda3\envs\pytorch\python.exe E:/IPIC-AWAN-master/AWAN_Clean/train/main.py
> 
> loading dataset ...
> Train1:0,Train2:0,Train3:0,Train4:0,
> Validation set samples: 0
> 
> building models_baseline ...
> Parameters number is 17461617
> Traceback (most recent call last):
> File "E:/IPIC-AWAN-master/AWAN_Clean/train/main.py", line 186, in
> main()
> File "E:/IPIC-AWAN-master/AWAN_Clean/train/main.py", line 95, in main
> train_loss, iteration, lr = train(train_loader, model, criterion_train, optimizer, epoch, iteration, opt.init_lr, opt.decay_power, opt.trade_off)
> File "E:/IPIC-AWAN-master/AWAN_Clean/train/main.py", line 145, in train
> return losses.avg, iteration, lr
> UnboundLocalError: local variable 'lr' referenced before assignment

Please run data pre-processing firstly.

**Comment by msn321** [comment]
I know, I follow your README, but can't

**Comment by Fern-Luiz** [comment]
Hello, while the paper shows  MRAE 0.06+ on Real world NTIRE 2020,  I use AWAN+ algorithm to test the validation set (provided by competition in google drive)on real word but get MRAE 0.1+. Do you have any different tricks that not published in your paper?

**Comment by JackWhite-rwx** [comment]
> 您可以在“https://competitions.codalab.org/competitions/22225”链接的参与选项卡中获取它。

这个比赛已经结束了，这个链接也无法再下载数据了，请问有保存当时训练和验证的数据吗？如果有的话，可否通过网盘链接分享一下？非常感谢您杰出的工作！

**Comment by Deep-imagelab** [comment]
我把数据传好了，有效期是30天，你们可以尽快下载下。

链接：https://pan.baidu.com/s/1BjvPWlXbjGxmuUZmH5tnGw 

提取码：2022










在 2022-09-30 15:02:45，"img_wcx1120" ***@***.***> 写道：







这个比赛说明写了，只有注册成为参赛者（审核通过需要1-2天），才能获取数据，你们可以看看。
我这边不太确定我能不能传数据到网盘（不知道会不会侵权啥的），这个数据集本身也很大，有20多G，我这两天可以先传一下，到时候我可能只敢开放有限的时间供你们下载，就担心侵权啥的。










在 2022-09-30 11:44:18，"JackWhite-rwx" ***@***.***> 写道：

您可以在“https://competitions.codalab.org/competitions/22225”链接的参与选项卡中获取它。

这个比赛已经结束了，这个链接也无法再下载数据了，请问有保存当时训练和验证的数据吗？如果有的话，可否通过网盘链接分享一下？非常感谢您杰出的工作！

**Comment by Deep-imagelab** [comment]
这个比赛说明写了，只有注册成为参赛者（审核通过需要1-2天），才能获取数据，你们可以看看。
我这边不太确定我能不能传数据到网盘（不知道会不会侵权啥的），这个数据集本身也很大，有20多G，我这两天可以先传一下，到时候我可能只敢开放有限的时间供你们下载，就担心侵权啥的。










在 2022-09-30 11:44:18，"JackWhite-rwx" ***@***.***> 写道：

您可以在“https://competitions.codalab.org/competitions/22225”链接的参与选项卡中获取它。

这个比赛已经结束了，这个链接也无法再下载数据了，请问有保存当时训练和验证的数据吗？如果有的话，可否通过网盘链接分享一下？非常感谢您杰出的工作！

**Comment by msn321** [comment]
好的，谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Deep-imagelab/AWAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月1日(星期六) 下午4:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Deep-imagelab/AWAN] Train data (#2)





 
 
 
 我把数据传好了，有效期是30天，你们可以尽快下载下。
 
 链接：https://pan.baidu.com/s/1BjvPWlXbjGxmuUZmH5tnGw 
 
 提取码：2022
 
 
 
 
 
 
 
 
 
 
 在 2022-09-30 15:02:45，"img_wcx1120" ***@***.***&gt; 写道：
 
 
 
 
 
 
 
 这个比赛说明写了，只有注册成为参赛者（审核通过需要1-2天），才能获取数据，你们可以看看。
 我这边不太确定我能不能传数据到网盘（不知道会不会侵权啥的），这个数据集本身也很大，有20多G，我这两天可以先传一下，到时候我可能只敢开放有限的时间供你们下载，就担心侵权啥的。
 
 
 
 
 
 
 
 
 
 
 在 2022-09-30 11:44:18，"JackWhite-rwx" ***@***.***&gt; 写道：
 
 您可以在“https://competitions.codalab.org/competitions/22225”链接的参与选项卡中获取它。
 
 这个比赛已经结束了，这个链接也无法再下载数据了，请问有保存当时训练和验证的数据吗？如果有的话，可否通过网盘链接分享一下？非常感谢您杰出的工作！

**Comment by newshu** [comment]
@msn321 可以分享下百度链接吗？百度链接失效了:blush:

**Comment by Deep-imagelab** [comment]
> https://pan.baidu.com/s/1BjvPWlXbjGxmuUZmH5tnGw

链接: https://pan.baidu.com/s/1GMxU6ojEi98n134JYdnjMg 提取码: hkm3

**Comment by newshu** [comment]
@Deep-imagelab  感谢大佬。再冒昧问一下，我看见你在MST++下评论无法跑出作者论文公布的结果，我在2080TI上也没有跑出额，请问后续大佬在版本更改后跑出作者论文结果了吗？

**Comment by msn321** [comment]
我后来训练网络的时候没有直接使用MST++的源代码，而是仅用了MST++的网络结构，放在了我的代码框架下训练的。
你也可以试着改一下MST++的源代码，我记得好像是因为加载数据的那里会导致电脑内存不够用


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Deep-imagelab/AWAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月28日(星期一) 下午2:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Deep-imagelab/AWAN] Train data (#2)





 
@Deep-imagelab  感谢大佬。再冒昧问一下，我看见你在MST++下评论无法跑出作者论文公布的结果，我在2080TI上也没有跑出额，请问后续大佬在版本更改后跑出作者论文结果了吗？

**Comment by Deep-imagelab** [comment]
> @Deep-imagelab 感谢大佬。再冒昧问一下，我看见你在MST++下评论无法跑出作者论文公布的结果，我在2080TI上也没有跑出额，请问后续大佬在版本更改后跑出作者论文结果了吗？

我跑了几次也没跑出来，总是差一点点，可能是随机性的影响吧

**Comment by JackWhite-rwx** [comment]
我在3090上使用pytorch1.9.0_cu11.1跑的结果比论文里的高




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月29日(星期二) 晚上8:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Deep-imagelab/AWAN] Train data (#2)





  
@Deep-imagelab 感谢大佬。再冒昧问一下，我看见你在MST++下评论无法跑出作者论文公布的结果，我在2080TI上也没有跑出额，请问后续大佬在版本更改后跑出作者论文结果了吗？
  
我跑了几次也没跑出来，总是差一点点，可能是随机性的影响吧

**Comment by JackWhite-rwx** [comment]
好的，非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Deep-imagelab/AWAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月1日(星期六) 下午4:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Deep-imagelab/AWAN] Train data (#2)





 
 
 
 我把数据传好了，有效期是30天，你们可以尽快下载下。
 
 链接：https://pan.baidu.com/s/1BjvPWlXbjGxmuUZmH5tnGw 
 
 提取码：2022
 
 
 
 
 
 
 
 
 
 
 在 2022-09-30 15:02:45，"img_wcx1120" ***@***.***&gt; 写道：
 
 
 
 
 
 
 
 这个比赛说明写了，只有注册成为参赛者（审核通过需要1-2天），才能获取数据，你们可以看看。
 我这边不太确定我能不能传数据到网盘（不知道会不会侵权啥的），这个数据集本身也很大，有20多G，我这两天可以先传一下，到时候我可能只敢开放有限的时间供你们下载，就担心侵权啥的。
 
 
 
 
 
 
 
 
 
 
 在 2022-09-30 11:44:18，"JackWhite-rwx" ***@***.***&gt; 写道：
 
 您可以在“https://competitions.codalab.org/competitions/22225”链接的参与选项卡中获取它。
 
 这个比赛已经结束了，这个链接也无法再下载数据了，请问有保存当时训练和验证的数据吗？如果有的话，可否通过网盘链接分享一下？非常感谢您杰出的工作！

**Comment by jier008** [comment]
请问能否再分享一下数据集的百度云链接呢？之前的链接过期了，万分感谢
